import React from 'react';
import type { ProcessStage, Role } from './types';
import { 
    TruckIcon, 
    ScaleIcon, 
    BeakerIcon, 
    ArchiveBoxIcon, 
    CogIcon, 
    CubeIcon, 
    PaperAirplaneIcon, 
    ShieldCheckIcon,
    SparklesIcon 
} from './components/Icons';

export const PROCESS_STAGES: ProcessStage[] = [
    {
        id: 'arrival',
        name: 'Raw Dal Arrival',
        responsibleRole: 'Gate Entry Operator',
        erpModule: 'Arrival_Form',
        dependentOn: 'Supplier Schedule',
        output: 'Arrival Slip',
        description: 'Security logs incoming and outgoing vehicle details, including driver and broker information.',
        color: {
            bg: 'bg-gray-100',
            text: 'text-gray-800',
            border: 'border-gray-300'
        },
        icon: <TruckIcon />,
        formFields: [
            { name: 'gate_mode', label: 'Entry Type', type: 'text' }, // In or Out
            { name: 'timestamp', label: 'Timestamp', type: 'text' },
            { name: 'serial_number', label: 'Serial Number', type: 'text' },
            { name: 'vehicle_number', label: 'Vehicle Number', type: 'text' },
            { name: 'driver_name', label: 'Driver Name', type: 'text' },
            { name: 'phone_number', label: 'Driver Phone', type: 'tel' },
            { name: 'note', label: 'Note', type: 'textarea' },
            // IN-mode specific
            { name: 'from_broker', label: 'From Broker', type: 'text' },
            { name: 'to_location', label: 'To', type: 'text' },
            // OUT-mode specific
            { name: 'quantity', label: 'Quantity', type: 'number' },
            { name: 'from_location', label: 'From', type: 'text' },
            { name: 'broker_name', label: 'Broker Name', type: 'text' },
            { name: 'broker_phone', label: 'Broker Phone', type: 'tel' },
        ],
    },
    {
        id: 'weighing',
        name: 'Weighing',
        responsibleRole: 'Operator',
        erpModule: 'Weighing_Module',
        dependentOn: 'Vehicle Entry',
        output: 'Net Weight Slip',
        description: 'Gross and tare weights are recorded to determine the net weight of the materials.',
        color: {
            bg: 'bg-pink-100',
            text: 'text-pink-800',
            border: 'border-pink-300'
        },
        icon: <ScaleIcon />,
        formFields: [
            { name: 'weighing_heading', label: 'Weighing Machine', type: 'heading' },
            { name: 'vehicle_number', label: 'Vehicle No', type: 'text', placeholder: 'e.g., AP00XX0000' },
            { name: 'ticket_number', label: 'Ticket No', type: 'text', placeholder: 'Generated by device' },
            { name: 'note', label: 'Note', type: 'textarea', placeholder: 'Add any relevant notes' },
            { name: 'in_weight', label: 'In Weight', type: 'number', placeholder: 'e.g., 500.5 Quintal' },
            { name: 'out_weight', label: 'Out Weight', type: 'number', placeholder: 'e.g., 255.0 Quintal' },
            { name: 'sample_collector', label: 'Sample Collector', type: 'text', placeholder: 'e.g., John Doe' },
        ],
    },
    {
        id: 'quality_check_1',
        name: 'Initial Quality Check',
        responsibleRole: 'Quality Supervisor',
        erpModule: 'Quality_Module',
        dependentOn: 'Weighing',
        output: 'Quality Report',
        description: 'A sample is drawn for quality inspection. The batch is either approved for the next stage or rejected.',
        color: {
            bg: 'bg-red-100',
            text: 'text-red-800',
            border: 'border-red-300'
        },
        icon: <BeakerIcon />,
        formFields: [
            { name: 'quality_check_heading', label: 'Quality Check', type: 'heading' },
            { name: 'vehicle_number', label: 'Vehicle Number', type: 'text', placeholder: 'e.g., AP00XX0000' },
            { name: 'transaction_id', label: 'Transaction ID', type: 'text', placeholder: 'Auto-generated or manual' },
            { name: 'note', label: 'Note', type: 'textarea', placeholder: 'Add any notes here' },
            { name: 'size_analysis_7', label: '7 No', type: 'number', placeholder: '0' },
            { name: 'size_analysis_5', label: '5 No', type: 'number', placeholder: '0' },
            { name: 'size_analysis_4', label: '4 No', type: 'number', placeholder: '0' },
            { name: 'small_mud_percent', label: 'SM %', type: 'number', placeholder: '0' },
            { name: 'big_mud_stones_percent', label: 'LM %', type: 'number', placeholder: '0' },
            { name: 'damage_1', label: 'Damage 1', type: 'number', placeholder: '0' },
            { name: 'physical_damage_2', label: 'Damage 2', type: 'number', placeholder: '0' },
            { name: 'moisture_content_percent', label: 'Moisture %', type: 'number', placeholder: '0' },
            { name: 'upload_report', label: 'Upload Report', type: 'file' },
        ],
    },
    {
        id: 'bin_operation',
        name: 'Bin Operation',
        responsibleRole: 'Bin Operator',
        erpModule: 'Bin_Management',
        dependentOn: 'Initial Quality Check',
        output: 'Bin Assignment Log',
        description: 'Assigns quality-approved materials to specific storage bins for resting and processing.',
        color: {
            bg: 'bg-orange-100',
            text: 'text-orange-800',
            border: 'border-orange-300'
        },
        icon: <ArchiveBoxIcon />,
        formFields: [
            { name: 'bin_operation_heading', label: 'Bin Operation', type: 'heading' },
            { name: 'vehicle_number', label: 'Vehicle Number', type: 'dropdown' },
            { name: 'bin_status', label: 'Bin Status', type: 'dropdown', options: ['Fill', 'Discharge', 'Maintenance'] },
            { name: 'rm1', label: 'RM1', type: 'text', placeholder: 'Enter value' },
            { name: 'rm2', label: 'RM2', type: 'text', placeholder: 'Enter value' },
            { name: 'rm3', label: 'RM3', type: 'text', placeholder: 'Enter value' },
            { name: 'bins_heading', label: 'Bins', type: 'heading' },
            { name: 'ob_quantity', label: 'OB Quantity', type: 'number', placeholder: '0' },
            { name: 'cb_quantity', label: 'CB Quantity', type: 'number', placeholder: '0' },
            { name: 'wb_quantity', label: 'WB Quantity', type: 'number', placeholder: '0' },
            { name: 'pb_quantity', label: 'PB Quantity', type: 'number', placeholder: '0' },
            { name: 'sr_in_quantity', label: 'SR IN Quantity', type: 'number', placeholder: '0' },
            { name: 'hub_quantity', label: 'HUB Quantity', type: 'number', placeholder: '0' },
        ],
    },
    {
        id: 'cleaning',
        name: 'Cleaning',
        responsibleRole: 'Operator',
        erpModule: 'Cleaning_Module',
        dependentOn: 'Raw Dal Arrival',
        output: 'Cleaned Batch Log',
        description: 'Removal of dust, stones, and Other impurities from the raw dal.',
        color: {
            bg: 'bg-teal-100',
            text: 'text-teal-800',
            border: 'border-teal-300'
        },
        icon: <SparklesIcon />,
        formFields: [
            { name: 'batch_id', label: 'Batch ID', type: 'text', placeholder: 'e.g., CLN-20251027-001' },
            { name: 'machine_no', label: 'Machine No', type: 'text', placeholder: 'e.g., MC-05' },
        ],
    },
    {
        id: 'storage',
        name: 'Storage',
        responsibleRole: 'Store Manager',
        erpModule: 'Storage_Module',
        dependentOn: 'Quality Check',
        output: 'Stored Batch Record',
        description: 'The approved batch is assigned to storage bins for a 72-hour rest period.',
        color: {
            bg: 'bg-yellow-100',
            text: 'text-yellow-800',
            border: 'border-yellow-300'
        },
        icon: <ArchiveBoxIcon />,
        formFields: [
            { name: 'storage_heading', label: 'Storage Details', type: 'heading' },
            { name: 'entered_vehicle', label: 'Entered Vehicle', type: 'text', placeholder: 'e.g., AP00XX0000' },
            { name: 'quantity', label: 'Quantity (in Quintal)', type: 'number', placeholder: 'e.g., 250' },
            { name: 'material_content', label: 'Material Content', type: 'dropdown', options: ['M1', 'M2', 'M3', 'M4', 'M5'] },
            { name: 'jute_bags_quantity', label: 'Jute Bags Quantity', type: 'number', placeholder: 'e.g., 500' },
            { name: 'plastic_bags_quantity', label: 'Plastic Bags Quantity', type: 'number', placeholder: 'e.g., 0' },
            { name: 'location_main', label: 'Location (Area)', type: 'dropdown', options: ['Kallam', 'Baddi', 'Godown'] },
            { name: 'location_sub', label: 'Location (Unit)', type: 'dropdown' },
        ],
    },
    {
        id: 'processing',
        name: 'Processing',
        responsibleRole: 'Plant Operator',
        erpModule: 'Processing_Module',
        dependentOn: 'Storage',
        output: 'Processed Dal Output',
        description: 'Milling or splitting process, including de-husking, sorting, and grading.',
        color: {
            bg: 'bg-fuchsia-100',
            text: 'text-fuchsia-800',
            border: 'border-fuchsia-300'
        },
        icon: <CogIcon />,
        formFields: [
            { name: 'process_id', label: 'Process ID', type: 'text', placeholder: 'e.g., PROC-001' },
            { name: 'machine_id', label: 'Machine ID', type: 'text', placeholder: 'e.g., MILL-02' },
            { name: 'parameters', label: 'Parameters', type: 'textarea', placeholder: 'e.g., Grade A, Split' },
        ],
    },
    {
        id: 'quality_check_2',
        name: 'Final Quality Re-Check',
        responsibleRole: 'Quality Supervisor',
        erpModule: 'Quality_Module',
        dependentOn: 'Processing',
        output: 'Final QC Report',
        description: 'Ensures compliance of the processed dal before it moves to packing.',
        color: {
            bg: 'bg-red-100',
            text: 'text-red-800',
            border: 'border-red-300'
        },
        icon: <ShieldCheckIcon />,
        formFields: [
            { name: 'final_moisture_percent', label: 'Final Moisture (%)', type: 'number', placeholder: 'e.g., 11.0' },
            { name: 'split_percentage', label: 'Split Percentage', type: 'number', placeholder: 'e.g., 99.8' },
            { name: 'final_remarks', label: 'Final Remarks', type: 'textarea', placeholder: 'e.g., Ready for packing' },
        ],
    },
    {
        id: 'packing',
        name: 'Packing',
        responsibleRole: 'Packaging Supervisor',
        erpModule: 'Packing_Module',
        dependentOn: 'Final Quality Re-Check',
        output: 'Packed Goods Record',
        description: 'The finished product is packed into bags of various sizes (e.g., 25kg, 50kg).',
        color: {
            bg: 'bg-green-100',
            text: 'text-green-800',
            border: 'border-green-300'
        },
        icon: <CubeIcon />,
        formFields: [
            { name: 'packing_id', label: 'Packing ID', type: 'text', placeholder: 'e.g., PACK-001' },
            { name: 'bag_size_kg', label: 'Bag Size (kg)', type: 'dropdown', options: ['25', '50', '100'] },
            { name: 'no_of_bags', label: 'Number of Bags', type: 'number', placeholder: 'e.g., 200' },
        ],
    },
    {
        id: 'dispatch',
        name: 'Dispatch',
        responsibleRole: 'Logistics Officer',
        erpModule: 'Dispatch_Module',
        dependentOn: 'Packing',
        output: 'Dispatch Note / Gate Pass',
        description: 'Packed goods are loaded onto vehicles for delivery to clients or distribution centers.',
        color: {
            bg: 'bg-sky-100',
            text: 'text-sky-800',
            border: 'border-sky-300'
        },
        icon: <PaperAirplaneIcon />,
        formFields: [
            { name: 'dispatch_id', label: 'Dispatch ID', type: 'text', placeholder: 'e.g., DISP-001' },
            { name: 'destination', label: 'Destination', type: 'text', placeholder: 'e.g., Hyderabad Warehouse' },
            { name: 'truck_no', label: 'Truck No', type: 'text', placeholder: 'e.g., TS09AB1234' },
        ],
    }
];

export const ROLE_PERMISSIONS: Partial<Record<Role, string[]>> = {
    ADMIN: ['*'],
    MANAGER: ['*'],
    ASSISTANT_MANAGER: ['*'],
    GATE_ENTRY_OPERATOR: ['arrival'],
    OPERATOR: ['weighing', 'cleaning'],
    QUALITY_SUPERVISOR: ['quality_check_1', 'quality_check_2'],
    BIN_OPERATOR: ['bin_operation'],
    STORE_MANAGER: ['storage'],
    PLANT_OPERATOR: ['processing'],
    PACKAGING_SUPERVISOR: ['packing'],
    LOGISTICS_OFFICER: ['dispatch']
};
